### ISSUE TITLE
Not for Raspberry Pi 2 Model B

### ISSUE THREAD

**Issue by diskmaster23** [diy-electronics/raspberrypi-b-plus-case#2]
I tried your design out. I was disappointed to find out that your design is not for the Raspberry Pi 2 Model BB despite saying it was. Want proof? Here you go http://imgur.com/c0Akb3t . The screw holes don't even line up. I did not do any scaling or anything. 
Great design, but not for your Raspb Pi 2.

**Comment by diskmaster23** [comment]
I am going to try something different. Some people have informed me that it might have been an issue with Illustrator and scaling.

**Comment by aburnsni** [comment]
I've no idea whether it works with rpi2 or not, I only forked the project -
it is NOT my design.
Good luck
Andrew

**Comment by diskmaster23** [comment]
I apologize, it very well might be an issue between illustrator and the laser printer driver. I'll try something else and report back.

**Comment by sedrubal** [comment]
Ok I'm glad to hear that it isn't a problem of the design :D

Yes, illustrator has a problem with scaling. I know that exporting an svg misscales the drawing about 20%. This might be the problem in your case.

For the most lasercutters I can recommend inkscape & [visicut](https://github.com/t-oster/VisiCut).

**Comment by diskmaster23** [comment]
Do we have visicut?

-----
David Gutowsky
219-805-0541
My PGP Public Key: https://goo.gl/jo1SuU
